### ISSUE TITLE
Gserver library is not included in ruby stdlib

### ISSUE THREAD

**Issue by swaps19** [aarongough/mini-smtp-server#12]
Here you are requiring `gserver` library which was included as a part of ruby `stdlib`. But according to [this](https://bugs.ruby-lang.org/issues/5480) issue it is not anymore.

So I think the gem `gserver` should be included in `gemspec` for supporting with future ruby versions.

P.S. - I am currently working on `ruby-2.3.0`

**Comment by TomFreudenberg** [comment]
Hi @swaps19 - take a look at the https://github.com/4commerce-technologies-AG/midi-smtp-server. Its API compatible and works with Ruby 2.x and does not need GServer anymore.

**Comment by aarongough** [comment]
This project is no longer under active development and is no longer maintained. Please see MIDI SMTP Server for a possible replacement: https://github.com/4commerce-technologies-AG/midi-smtp-server
