### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by wvengen** [aarongough/mini-smtp-server#14]
The last released version on RubyGems [is 0.0.2](https://rubygems.org/gems/mini-smtp-server) from 2010. Since there have been some relevant commits since, please release a new version. This would help in keeping clean `Gemfile`s, pointing them to a canonical repository.

**Comment by TomFreudenberg** [comment]
Hi @wvengen - maybe take a look at the https://github.com/4commerce-technologies-AG/midi-smtp-server. Its API compatible and works with Ruby 2.x, does not need GServer anymore and fits other improvements.

**Comment by wvengen** [comment]
@TomFreudenberg thanks, I've started using that since. Useful to mention here :+1:

**Comment by aarongough** [comment]
Sorry guys, I am no longer actively maintaining this gem as I simply don't have any day-to-day use for it. I would suggest either forking the project and releasing an alternative gem, or using midi-smtp-server as suggested. If someone wants to take over mini-smtp-server as the new maintainer please reach out!

**Comment by TomFreudenberg** [comment]
Hey @aarongough 

I would suggest you to archive this project to avoid inconveniences for others. If you like - and that would make me happy - leave a clear note on top of the archive that midi-smtp-server allows a straight up path for any code stil based on mini-smtp-server.

Thanks for all the time and effort you spend into this component - hopefully midi-smtp-server is a worthy successor also in your sense.

Cheers
Tom

**Comment by aarongough** [comment]
Yeah I think that's reasonable, I will update and archive now!
