### ISSUE TITLE
Multiple gsub causing error

### ISSUE THREAD

**Issue by phil9690** [aarongough/mini-smtp-server#15]
When the line https://github.com/aarongough/mini-smtp-server/blob/master/lib/mini-smtp-server/mini-smtp-server.rb#L54 get hit, the first gsub returns `nil` and the second gsub returns an error, due to the nil. When I remove the second gsub everything works as expected. Is there a reason for the two gsubs here?

**Comment by aarongough** [comment]
This project is no longer under active development and is no longer maintained. Please see MIDI SMTP Server for a possible replacement: https://github.com/4commerce-technologies-AG/midi-smtp-server
