### ISSUE TITLE
EHLO verb and SMTP Extensions

### ISSUE THREAD

**Issue by kumy** [aarongough/mini-smtp-server#17]
I've that the current implementation does not respect the "The EHLO verb and SMTP extensions" https://cr.yp.to/smtp/ehlo.html

> EHLO is just like HELO except that the server's response text provides computer-readable information about the server's abilities.
> 
> Here is what happens if the server accepts EHLO (required code 250). On the first response line, the text begins with the server's name. On each response line past the first, the text is an extension, followed optionally by a space and an argument, followed optionally by a space and another argument, etc.
> 
> The extension is a nonempty string of letters, digits, and hyphens. Each argument is a nonempty string of graphical ASCII characters.
> 
> A rather extreme example:

```
     220 size.does.matter.af.MIL (More ESMTP than Crappysoft!)
     EHLO heaven.af.mil
     250-size.does.matter.af.MIL offers FIFTEEN extensions:
     250-8BITMIME
     250-PIPELINING
     250-DSN
     250-ENHANCEDSTATUSCODES
     250-EXPN
     250-HELP
     250-SAML
     250-SEND
     250-SOML
     250-TURN
     250-XADR
     250-XSTA
     250-ETRN
     250-XGEN
     250 SIZE 51200000
```

The actual response of `mini-smtp-server` is:
```$ telnet 127.0.0.1 25
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
220 hello
EHLO kumy.net
220 go on...
telnet> quit
Connection closed.
```

I see some problems here:
* After `EHLO`, we have `220 go on...` instead of `250 <server's name>`
* Even not sure `220` code is valid on a `EHLO` response.
This seems to have been fixed in #5 but my `gem install mini-smtp-server` doesn't contains this fix. have it been released? The gem found at https://rubygems.org/gems/mini-smtp-server was released in 2010 and this issue is from 2013.

The interesting part in https://tools.ietf.org/html/rfc5321#section-4.1.1.1 say

> A client SMTP SHOULD start an SMTP session by issuing the EHLO
>    command.  If the SMTP server supports the SMTP service extensions, it
>    will give a successful response, a failure response, or an error
>    response.  If the SMTP server, in violation of this specification,
>    does not support any SMTP service extensions,

If I understand this well, if `mini-smtp-server` supports extension it should report them, if it support none it should return an error. I'm wondering if it actually "support" some extension?

Regarding the response format it is stated:

>    Normally, the response to EHLO will be a multiline reply.  Each line
>    of the response contains a keyword and, optionally, one or more
>    parameters.  Following the normal syntax for multiline replies, these
>    keywords follow the code (250) and a hyphen for all but the last
>    line, and the code and a space for the last line.

So clearly, `220` seems invalid.

Technically, I'm looking for the extension [`8BITMIME`](https://cr.yp.to/smtp/8bitmime.html) as in #16 and really wondering if it's "available/supported" here.

https://cr.yp.to/smtp/8bitmime.html
> 7-bit mailers are obsolete. Do not attempt to deploy a 7-bit mailer on the Internet.

 I hope it is!

A list of standard extension is listed here https://cr.yp.to/smtp/ehlo.html

Related to https://github.com/bcosca/fatfree-core/issues/328#L189

**Comment by aarongough** [comment]
This project is no longer under active development and is no longer maintained. Please see MIDI SMTP Server for a possible replacement: https://github.com/4commerce-technologies-AG/midi-smtp-server
