### ISSUE TITLE
Improved component - midi-smtp-server

### ISSUE THREAD

**Issue by TomFreudenberg** [aarongough/mini-smtp-server#8]
Hi, first of all thanks for your inspiration work. In case that we wished to change something on design and also allow more events and information from smtp server communications, we decided to create a ne / improved version of your library.

If you are interested in, please have a look at:

https://github.com/TomFreudenberg/midi-smtp-server

Thanks, Tom

**Comment by TomFreudenberg** [comment]
Hi out there, a new release is available - also handled suggestion from @hron84 

@aarongough - maybe you also like to add some note about midi-smtp-server to your README.md and close this issue.

Thanks,
Tom

**Comment by aarongough** [comment]
I added a note at the bottom of the readme!

**Comment by TomFreudenberg** [comment]
Thanks Aaron!
