### ISSUE TITLE
Missing dependency gserver

### ISSUE THREAD

**Issue by kjarnet** [aarongough/mini-smtp-server#9]
Hi!
When I try running mini-smtp-server I get the following error:
```sh
LoadError: cannot load such file -- gserver
/Users/kjarnet/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini-smtp-server-0.0.2/lib/mini-smtp-server/mini-smtp-server.rb:1:in `require'
/Users/kjarnet/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini-smtp-server-0.0.2/lib/mini-smtp-server/mini-smtp-server.rb:1:in `<top (required)>'
/Users/kjarnet/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini-smtp-server-0.0.2/lib/mini-smtp-server.rb:1:in `require'
/Users/kjarnet/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini-smtp-server-0.0.2/lib/mini-smtp-server.rb:1:in `<top (required)>'
```
Is this a dependency of mini-smtp-server that should've been listed in your gemfile (forgive me if I'm asking stupid questions - I'm new to ruby)?
This seems like a really nice app - hope you can help me getting it running. Thanks in advance :)

**Comment by aarongough** [comment]
I think this might be an incompatibility with the Ruby version... I developed mini-smtp-server on ruby 1.9.3, and I can see you're using 2.2.2

It looks like newer versions of Ruby removed the Gserver class from the standard library and made it a gem instead. Add 'gserver' to your project's Gemfile and things should work again!

-Aaron

**Comment by kjarnet** [comment]
Thanks for the quick reply!
Adding gserver fixed this problem, so I'm closing this issue :) Sadly, I still couldn't get it to work (only replied with 500 ERROR), but I found another solution so I'm not going to pursue this any further.
Thanks for helping, and for sharing so generously of your work and time! :)
